/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'romanovi' at '2/7/17 1:55 PM' with Gradle 3.2.1
 *
 * @author romanovi, @date 2/7/17 1:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
